
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###

GET http://localhost:8000/products/eece389c-9269-425b-a5f3-39e4709f52fd


###
PUT http://localhost:8000/products/eece389c-9269-425b-a5f3-39e4709f52fd
Content-Type: application/json

{
    "name": "My Updated",
    "price": 100
}

###
DELETE  http://localhost:8000/products/eece389c-9269-425b-a5f3-39e4709f52fd
Content-Type: application/json


###

GET http://localhost:8000/products


###

POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "victor",
    "email": "hugo@gmail.com",
    "password": "123456"
}
###
POST http://localhost:8000/users/generate_token
Content-Type: application/json

{
   "Email": "hugo@gmail.com",
    "password": "123456"
}
