
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "My Product",
    "price": 100
}

###

GET http://localhost:8000/products/eece389c-9269-425b-a5f3-39e4709f52fd


###
PUT http://localhost:8000/products/eece389c-9269-425b-a5f3-39e4709f52fd
Content-Type: application/json

{
    "name": "My Updated",
    "price": 100
}

###
DELETE  http://localhost:8000/products/eece389c-9269-425b-a5f3-39e4709f52fd
Content-Type: application/json


###

GET http://localhost:8000/products

